[
  {
    "BTTActionCategory": 0,
    "BTTLastUpdatedAt": 1742697650.905817,
    "BTTTriggerType": 102,
    "BTTTriggerTypeDescriptionReadOnly": "3 Finger Swipe Up",
    "BTTTriggerClass": "BTTTriggerTypeTouchpadAll",
    "BTTUUID": "F021A0B9-5C64-4DAD-B68A-5F142A23D267",
    "BTTPredefinedActionType": 186,
    "BTTPredefinedActionName": "⌘ CMD Key Down",
    "BTTGenericActionConfig2": "0",
    "BTTGenericActionConfig": "1000",
    "BTTEnabled": 1,
    "BTTEnabled2": 1,
    "BTTOrder": 5,
    "BTTAdditionalActions":
      [
        {
          "BTTActionCategory": 0,
          "BTTLastUpdatedAt": 1742630159.6423111,
          "BTTTriggerParentUUID": "F021A0B9-5C64-4DAD-B68A-5F142A23D267",
          "BTTIsPureAction": true,
          "BTTTriggerClass": "BTTTriggerTypeTouchpadAll",
          "BTTUUID": "CCD51876-61F6-4A6C-A689-815224FE4FC3",
          "BTTLayoutIndependentActionChar": "t",
          "BTTAdditionalActionData": { "sendCurrentModifiers": true },
          "BTTGenericActionConfig2": "onlyDown",
          "BTTShortcutToSend": "17",
          "BTTShortcutUpDown": "onlyDown",
          "BTTEnabled": 1,
          "BTTEnabled2": 1,
          "BTTOrder": 0,
        },
        {
          "BTTActionCategory": 0,
          "BTTLastUpdatedAt": 1742630105.987484,
          "BTTTriggerParentUUID": "F021A0B9-5C64-4DAD-B68A-5F142A23D267",
          "BTTIsPureAction": true,
          "BTTTriggerClass": "BTTTriggerTypeTouchpadAll",
          "BTTUUID": "DE46BF94-3076-4FC7-B79A-987C0BACBBFE",
          "BTTPredefinedActionType": 129,
          "BTTPredefinedActionName": "Pause Execution or Delay Next Action (blocking)",
          "BTTDelayNextActionBy": "0.3",
          "BTTEnabled": 1,
          "BTTEnabled2": 1,
          "BTTOrder": 1,
        },
        {
          "BTTActionCategory": 0,
          "BTTLastUpdatedAt": 1742630163.6112289,
          "BTTTriggerParentUUID": "F021A0B9-5C64-4DAD-B68A-5F142A23D267",
          "BTTIsPureAction": true,
          "BTTTriggerClass": "BTTTriggerTypeTouchpadAll",
          "BTTUUID": "97383B56-1EDD-43A8-84D3-F3299CC48612",
          "BTTLayoutIndependentActionChar": "t",
          "BTTAdditionalActionData": { "sendCurrentModifiers": true },
          "BTTGenericActionConfig2": "onlyUp",
          "BTTShortcutToSend": "17",
          "BTTShortcutUpDown": "onlyUp",
          "BTTEnabled": 1,
          "BTTEnabled2": 1,
          "BTTOrder": 2,
        },
        {
          "BTTActionCategory": 0,
          "BTTLastUpdatedAt": 1742630105.9873719,
          "BTTTriggerParentUUID": "F021A0B9-5C64-4DAD-B68A-5F142A23D267",
          "BTTIsPureAction": true,
          "BTTTriggerClass": "BTTTriggerTypeTouchpadAll",
          "BTTUUID": "6309C11C-0063-4E9B-A962-9763F9C2624F",
          "BTTPredefinedActionType": 187,
          "BTTPredefinedActionName": "⌘ CMD Key Up",
          "BTTEnabled": 1,
          "BTTEnabled2": 1,
          "BTTOrder": 3,
        },
      ],
  },
]
